### PR TITLE
Test resources in test env

### PR DESCRIPTION
**Pull request by TheoLeanse**
/cc @matthew-andrews 
more...

### CODE REVIEW

**Comment by TheoLeanse** [comment]
I think it's ok to leave this as is:

https://github.com/Financial-Times/next-url-management-api/pull/181/files#diff-a2437e7edb9c083bb8b302fc9f4c26f8R53

**Comment by matthew-andrews** [comment]
hmm, ideally the test archive should archivet he test dbs :/

**Comment by matthew-andrews** [comment]
oh no you're right i think it's fine

**Comment by matthew-andrews** [comment]
aw, sorry about the duplication

**Comment by TheoLeanse** [comment]
I think that's all the places we need to differentiate environment?

**Comment by matthew-andrews** [comment]
think so…

**Comment by matthew-andrews** [comment]
the critical one is the API

**Comment by matthew-andrews** [comment]
which is laready done

**Pull request merged**
