### PR TITLE
Deploy test infrastructure into production account

### PR DESCRIPTION
**Pull request by TheoLeanse**
/cc @matthew-andrews 

how do you feel about this, a test template rather than putting all of this in the master.json template or trying to do something with an environment parameter and conditionals?

### CODE REVIEW

**Comment by matthew-andrews** [comment]
what needs to be conditional?

**Comment by matthew-andrews** [comment]
i think ideally one template for each environment is ideal……

**Comment by TheoLeanse** [comment]
conditionals a bit like sitemaps: https://github.com/Financial-Times/next-sitemaps/blob/master/templates/master.json#L10

but yes so good to go with this separate template then?

**Comment by matthew-andrews** [comment]
i mean, in this app, what needs to be conditional?  which resources?

**Comment by TheoLeanse** [comment]
the backup bucket? and names, probably?

**Comment by matthew-andrews** [comment]
just the names i think……?
i think it would be much better if we can keep test+prod in the same CF template……

**Comment by TheoLeanse** [comment]
aha ok I will see to it

**Pull request merged**
