### PR TITLE
increase default provisioned throughput

### PR DESCRIPTION
**Pull request by TheoLeanse**
@matthew-andrews @commuterjoy

### CODE REVIEW

**Comment by ookejimift** [comment]
👍

**Comment by matthew-andrews** [comment]
it's not necessary to update this

**Comment by matthew-andrews** [comment]
you can can just tweak the provisioned amount in the aws console

**Comment by TheoLeanse** [comment]
yep but thought these default values could be misleading - though I suppose people would be checking the console rather than the cloudformation template for this info

**Comment by matthew-andrews** [comment]
ok fair enough… although it looks like we don't actually need this capacity, we need to fix whatever bug is there :/

**Pull request closed without merging**
